In [1]:
!pip install pandas requests duckdb ratelimit

Requirement already satisfied: pandas in /usr/local/python/3.14.2/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: requests in /home/codespace/.local/lib/python3.14/site-packages (2.34.2)
Requirement already satisfied: duckdb in /usr/local/python/3.14.2/lib/python3.14/site-packages (1.5.6)
Requirement already satisfied: ratelimit in /usr/local/python/3.14.2/lib/python3.14/site-packages (2.2.1)
Requirement already satisfied: numpy>=2.3.3 in /usr/local/python/3.14.2/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/.local/lib/python3.14/site-packages (from requests) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.14/site-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in /home/codespace/.local/lib/python3.14/site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /home/codespace/.local/lib/python3.14/site-packages (from requests) (2026.7.22)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python3 -m pip install --upgrade pip

In [2]:
import pandas as pd 
import requests 
import pandas as pd 
import duckdb
import os
from ratelimit import limits, sleep_and_retry

In [3]:
api_key = os.environ.get("TMDB_APIKEY")
if not api_key:
   raise ValueError("API KEY missing")

In [4]:
headers = {"accept": "application/json", "Authorization": f"Bearer {api_key}"}
# movie_url = f"https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&primary_release_date.gte=2024-01-01&sort_by=popularity.desc&vote_average.gte=7&vote_count.gte=1000"
tv_url = "https://api.themoviedb.org/3/discover/tv?include_adult=false&include_null_first_air_dates=false&language=en-US&page=1&sort_by=popularity.desc"
persons_url = "https://api.themoviedb.org/3/person/popular?language=en-US&page=1"

In [6]:
@sleep_and_retry
@limits(calls = 25, period = 1)
def extract_movie_ids(date = "2024-01-01", rating=7.0, votes=1000, max_pages=10):
    """
    Extract movie_ids from TMDB API. This method is better bcos it allows getting more movie info from movie details on tmdb
    
    Args:
        date (str): The minimum release date of the movies to be fetched. Format: YYYY-MM-DD
        rating (float): The minimum average rating of the movies to be fetched.
        votes (int): The minimum number of votes of the movies to be fetched.
        max_pages (int): The maximum number of pages to fetch. Each page contains 20 movies.
        """
        
    date = str(date)
    rating = float(rating)
    votes = int(votes)
    max_pages =int(max_pages)

    movie_url = f"https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&primary_release_date.gte={date}&sort_by=popularity.desc&vote_average.gte={rating}&vote_count.gte={votes}"
    
    response = requests.get(url=movie_url, headers=headers)
    data = response.json()
    total_pages = data.get("total_pages")
    if total_pages > max_pages:
        print(f"Requesting too many pages. The maximum is {max_pages} pages. Stopping fetch.")
        return        
    
    try:
        all_movies = []
        for num in range(1, total_pages + 1):
            movie_url = f"https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page={num}&primary_release_date.gte={date}&sort_by=popularity.desc&vote_average.gte={rating}&vote_count.gte={votes}"

            response = requests.get(url=movie_url, headers=headers)

            data = response.json()
            movies_on_page = data.get("results", [])
            all_movies.extend(movies_on_page)
        
        ids = [all_movies[x].get('id') for x in range(len(all_movies))]
        return list(dict.fromkeys(ids)) # checking that the ids are not duplicates by converting it to dict and back to list. dict disallows duplicates and retains order
                
            # print(f"Fetched page {num} of {total_pages}") 
    except Exception as e:
        print(f'An unexpected error occured: {e}')
    
movie_ids = extract_movie_ids()

In [7]:
# # len(all_movies)
# movie_ids = [all_movies[x].get('id') for x in range(len(all_movies))]
# len(list(dict.fromkeys(movie_ids)))
len(movie_ids)

107

In [8]:
@sleep_and_retry
@limits(calls=25, period=1)
def extract_movie_details():
    """
    Extracting movie details using the movie id
    """
    movie_ids = extract_movie_ids()
    details = []
    for movie_id in movie_ids:
        try:
            url = f"https://api.themoviedb.org/3/movie/{movie_id}?language=en-US"
            response = requests.get(url=url, headers=headers)
            data = response.json()
            details.append(data)
        except Exception as e:
            print(f'An unexpected error occured: {e}')
    return details

movie_details= extract_movie_details()

In [62]:
movie_details[0]

{'adult': False,
 'backdrop_path': '/r08LxMJCbf1SiJIWeyH9aJmdqwC.jpg',
 'belongs_to_collection': {'id': 531241,
  'name': 'Spider-Man (MCU) Collection',
  'poster_path': '/yeba3Y820OjApZO9aJevDsNeMEd.jpg',
  'backdrop_path': '/AvnqpRwlEaYNVL6wzC4RN94EdSd.jpg'},
 'budget': 225000000,
 'genres': [{'id': 878, 'name': 'Science Fiction'},
  {'id': 28, 'name': 'Action'},
  {'id': 12, 'name': 'Adventure'}],
 'homepage': 'https://spidermanbrandnewday.movie',
 'id': 969681,
 'imdb_id': 'tt22084616',
 'origin_country': ['US'],
 'original_language': 'en',
 'original_title': 'Spider-Man: Brand New Day',
 'overview': "Fighting crime full-time as Spider-Man in a world that doesn't remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.",
 'popularity': 1227.7402,
 'poster_path': '/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg',
 'production_companies': [{'id': 420,
   'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
   'name': 'Marvel Studios',
   'origin_country': 'US'},
  {'id': 5,
   'logo_path': '/71BqEFAF4V3qjjMPCpLuyJFB9A.png',
   'name': 'Columbia Pictures',
   'origin_country': 'US'},
  {'id': 84041,
   'logo_path': '/nw4kyc29QRpNtFbdsBHkRSFavvt.png',
   'name': 'Pascal Pictures',
   'origin_country': 'US'},
  {'id': 22213,
   'logo_path': '/qx9K6bFWJupwde0xQDwOvXkOaL8.png',
   'name': 'TSG Entertainment',
   'origin_country': 'US'}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'}],
 'release_date': '2026-07-29',
 'revenue': 2516291000,
 'runtime': 145,
 'softcore': False,
 'spoken_languages': [{'english_name': 'English',
   'iso_639_1': 'en',
   'name': 'English'}],
 'status': 'Released',
 'tagline': 'A brand new day starts now.',
 'title': 'Spider-Man: Brand New Day',
 'video': False,
 'vote_average': 8.468,
 'vote_count': 5983}

In [74]:
movies = pd.DataFrame(movie_details)
movie_details_df = movies.copy()
movie_details_df.columns

Index(['adult', 'backdrop_path', 'belongs_to_collection', 'budget', 'genres',
       'homepage', 'id', 'imdb_id', 'origin_country', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'softcore', 'spoken_languages', 'status',
       'tagline', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='str')

In [75]:
movie_details_df.drop(columns = ['adult','homepage', 'belongs_to_collection', 'imdb_id', 'origin_country', 'original_title',  'production_countries', 'softcore', 'spoken_languages', 'video'], inplace=True)  
movie_details_df.head(3)

,backdrop_path,budget,genres,id,original_language,overview,popularity,poster_path,production_companies,release_date,revenue,runtime,status,tagline,title,vote_average,vote_count
0,/r08LxMJCbf1SiJIWeyH9aJmdqwC.jpg,225000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",969681,en,Fighting crime full-time as Spider-Man in a wo...,1227.7402,/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2026-07-29,2516291000,145,Released,A brand new day starts now.,Spider-Man: Brand New Day,8.468,5983
1,/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg,200000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",687163,en,Science teacher Ryland Grace wakes up on a spa...,1019.0916,/iOb2fjXLbpJgyQXe46n1WtGCnaa.jpg,"[{'id': 77973, 'logo_path': '/fAajboa3w8LNvweN...",2026-03-15,684586806,157,Released,Believe in the Hail Mary.,Project Hail Mary,8.635,8448
2,/nVBzWBqHTB3XD0iqWiJLfKLo5fq.jpg,250000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",1368337,en,"Odysseus, the legendary King of Ithaca, embark...",423.1889,/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,"[{'id': 33, 'logo_path': '/8lvHyhjr8oUKOOy2dKX...",2026-07-15,1788792045,173,Released,Defy the gods.,The Odyssey,8.015,4220

In [97]:
# making a df copy allows this cell to be run more than once without error. Df copy not applied in script
movie_details_df['genres'] = movies['genres'].apply(lambda x: [d['id'] for d in x])
movie_details_df['production_companies'] = movies['production_companies'].apply(lambda x: [d['id'] for d in x])
movie_details_df.head(2)

,backdrop_path,budget,genre_ids,movie_id,original_language,overview,popularity,poster_path,production_company_ids,release_date,revenue,runtime,status,tagline,title,vote_average,vote_count,release_date_id,genres,production_companies
0,/r08LxMJCbf1SiJIWeyH9aJmdqwC.jpg,225000000,"[878, 28, 12]",969681,en,Fighting crime full-time as Spider-Man in a wo...,1227.7402,/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg,"[420, 5, 84041, 22213]",2026-07-29,2516291000,145,Released,A brand new day starts now.,Spider-Man: Brand New Day,8.468,5983,20260729,"[878, 28, 12]","[420, 5, 84041, 22213]"
1,/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg,200000000,"[878, 12]",687163,en,Science teacher Ryland Grace wakes up on a spa...,1019.0916,/iOb2fjXLbpJgyQXe46n1WtGCnaa.jpg,"[77973, 210099, 84041, 232193, 22842]",2026-03-15,684586806,157,Released,Believe in the Hail Mary.,Project Hail Mary,8.635,8448,20260315,"[878, 12]","[77973, 210099, 84041, 232193, 22842]"

In [78]:
extracted_genres = [genre for x in range(len(movie_details)) for genre in movie_details[x]['genres']]
extracted_prod_companies = [company for x in range(len(movie_details)) for company in movie_details[x]['production_companies']]
dim_genre_df = pd.DataFrame(extracted_genres).drop_duplicates().reset_index(drop=True)
dim_prod_company_df = pd.DataFrame(extracted_prod_companies).drop_duplicates().reset_index(drop=True)[['id', 'name']]
dim_genre_df.head(3)

    id             name
0  878  Science Fiction
1   28           Action
2   12        Adventure

In [80]:
movie_details_df.columns

Index(['backdrop_path', 'budget', 'genre_ids', 'movie_id', 'original_language',
       'overview', 'popularity', 'poster_path', 'production_company_ids',
       'release_date', 'revenue', 'runtime', 'status', 'tagline', 'title',
       'vote_average', 'vote_count'],
      dtype='str')

In [95]:
movie_details_df['release_date_id'] = movie_details_df['release_date'].apply(lambda x: x.replace('-', ''))
movie_details_df['release_date_id'].head(2)

0    20260729
1    20260315
Name: release_date_id, dtype: str

In [96]:
dim_genre_df.columns = ['genre_id', 'genre_name']
dim_prod_company_df.columns = ['production_company_id', 'production_company_name']
movie_details_df.rename(columns={'id': 'movie_id',
                                 'genres': 'genre_ids',
                                 'production_companies': 'production_company_ids'}, inplace=True)

In [87]:
with duckdb.connect("movies_warehouse.duckdb") as con: 
    con.execute("""
        CREATE TABLE IF NOT EXISTS dim_date (
            date_id INTEGER PRIMARY KEY,
            full_date DATE,
            year INTEGER,
            quarter INTEGER,
            month INTEGER, 
            month_name VARCHAR,
            day_of_week VARCHAR,
            is_weekend BOOLEAN
        );

        CREATE TABLE IF NOT EXISTS dim_genre (
            genre_id INTEGER PRIMARY KEY,
            genre_name VARCHAR
        );

        CREATE TABLE IF NOT EXISTS dim_movie (
            movie_id INTEGER PRIMARY KEY,
            title VARCHAR,
            overview TEXT,
            tagline TEXT,
            original_language VARCHAR,
            status VARCHAR,
            poster_path VARCHAR,
            production_company_ids INTEGER[],
            genre_ids INTEGER[] 
        );

        CREATE TABLE IF NOT EXISTS fact_movie (
            movie_id INTEGER PRIMARY KEY,
            release_date_id INTEGER,
            runtime INTEGER, 
            vote_average DECIMAL(3,1),
            vote_count INTEGER,
            popularity DECIMAL(10,3),
            budget INTEGER,
            revenue BIGINT
            
        );

        CREATE TABLE IF NOT EXISTS dim_production_company (
            production_company_id INTEGER PRIMARY KEY,
            production_company_name VARCHAR
        );
        """
)

In [85]:
with duckdb.connect("movies_warehouse.duckdb") as con:
    print(con.execute("drop table dim_movie;").df())

Empty DataFrame
Columns: [Success]
Index: []

Loading into database

In [ ]:
with duckdb.connect("movies_warehouse.duckdb") as con:
    con.execute("""
        INSERT OR REPLACE INTO dim_genre (genre_id, genre_name)
        SELECT
            genre_id::INTEGER,
            genre_name::VARCHAR
        FROM dim_genre_df;

        
        INSERT OR REPLACE INTO dim_production_company (production_company_id, production_company_name)
        SELECT         
            production_company_id::INTEGER,
            production_company_name::VARCHAR
        FROM dim_prod_company_df;

        INSERT OR REPLACE INTO dim_movie(movie_id, title, overview, tagline, original_language, status, poster_path, production_company_ids, genre_ids)
        SELECT 
            movie_id::INTEGER,
            title::VARCHAR,
            overview::TEXT,
            tagline::TEXT,
            original_language::VARCHAR,
            status::VARCHAR,
            poster_path::VARCHAR,
            production_company_ids::INTEGER[],
            genre_ids::INTEGER[]
        FROM movie_details_df;

        
        INSERT OR REPLACE INTO fact_movie(movie_id, release_date_id, runtime, vote_average, vote_count, popularity, budget, revenue)
        SELECT 
            movie_id::INTEGER,
            release_date_id::INTEGER,
            runtime::INTEGER,
            vote_average::DECIMAL(3,1) as vote_average,
            vote_count::INTEGER as vote_count,
            popularity::DECIMAL(10,3) as popularity,
            budget::INTEGER as budget,
            revenue::BIGINT as revenue
        FROM movie_details_df;


        INSERT OR REPLACE INTO dim_date(date_id, full_date, year, quarter, month, month_name, day_of_week, is_weekend)
        SELECT 
            release_date_id::INTEGER as date_id,
            release_date::DATE as full_date,
            year(release_date::DATE) as year,
            quarter(release_date::DATE) as quarter,
            month(release_date::DATE) as month,
            strftime(release_date::DATE, '%B') as month_name,
            strftime(release_date::DATE, '%w') as day_of_week,
            CASE WHEN EXTRACT(DOW FROM release_date::DATE) IN (0, 6) THEN TRUE ELSE FALSE END as is_weekend
        FROM movie_details_df

""")
    print("Insert Successful!!")

Insert Successful!!

In [94]:
import duckdb
import pandas as pd
con = duckdb.connect("movies_warehouse.duckdb")
con.execute("""
    select * from dim_date
    limit 5
    """).df()

,date_id,full_date,year,quarter,month,month_name,day_of_week,is_weekend
0,20260715,2026-07-15,2026,3,7,July,3,False
1,20260916,2026-09-16,2026,3,9,September,3,False
2,20260610,2026-06-10,2026,2,6,June,3,False
3,20260513,2026-05-13,2026,2,5,May,3,False
4,20260812,2026-08-12,2026,3,8,August,3,False

In [ ]:
try:
    response = requests.get(url=movie_url, headers=headers)
    data= response.json()
except Exception as e:
    print(f'An unexpected error occured: {e}')

In [7]:
import requests
networks = []
for network_id in range(555, 558):
    url = f"https://api.themoviedb.org/3/network/{network_id}"

# headers = {
#     "accept": "application/json",
#     "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxNjZiNTdhMTBkMTQyNmVmMTQ0NGJmNTFjODBkYzg5ZSIsIm5iZiI6MTc5MTY0OTI0MC42ODQsInN1YiI6IjZhY2E2NWQ4NzdhMjhiYmQxOGYwZmU4YyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.uxXhuUGB1Klf9jpXfjREL4WEIwMxRP1sVlVj-jz8CKA"
# }

    response = requests.get(url, headers=headers)
    # network_respon
    print(response.text)

{"headquarters":"","homepage":"http://www.tvp.pl/","id":555,"logo_path":"/oq606JVmXAWtp6BeUqSSFdsp64O.png","name":"TVP","origin_country":"PL"}
{"headquarters":"Vilvoorde","homepage":"http://www.vtm.be","id":556,"logo_path":"/wpPJM99T9qkKvK16nRciNL2y64Q.png","name":"VTM","origin_country":"BE"}
{"headquarters":"","homepage":"","id":557,"logo_path":null,"name":"Community Channel","origin_country":"GB"}

In [27]:
data['results'][1].keys()

dict_keys(['adult', 'backdrop_path', 'genre_ids', 'id', 'title', 'original_language', 'original_title', 'overview', 'popularity', 'poster_path', 'release_date', 'softcore', 'video', 'vote_average', 'vote_count'])

In [ ]:
import pandas as pd 
import duckdb
import time

# df = pd.DataFrame(data['results'])
#df.head()

## Create the Star Schema tables

In [ ]:
# [item for item in dir(response) if not item.startswith("_") and not callable(getattr(response, item))]

In [ ]:
# BASE_URL = 'https://api.aviationstack.com/v1/'

# api_key = os.environ.get("AVIATIONSTACK_APIKEY")

# if api_key:
#     print(f"Secret found: {api_key[:4]}...")
# else:
#     print("Secret not found")

Secret found: 318c...

In [ ]:
all_movies = []

@sleep_and_retry
@limits(calls=25, period=1)
def extract_top_movies(date: str = "2024-01-01", rating: float = 7.0, voters: int = 1000, num_pages=6):
    """
    Extracting top movies released after 1st January 2024 with an average rating greater than 7.0 with not less than 1000 rating votes 
    """
    try:

        movie_url = f"https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&primary_release_date.gte={date}&sort_by=popularity.desc&vote_average.gte={rating}&vote_count.gte={voters}"

        for num in range(1, num_pages + 1):
            response = requests.get(url=movie_url, headers=headers)

            data = response.json()
            movies_on_page = data.get("results", [])
            all_movies.extend(movies_on_page)
                
            print(f"Fetched page {num} of {num_pages}")      
        return 
    except Exception as e:
        print(f'An unexpected error occured: {e}')

extract_top_movies()

Fetched page 1 of 6
Fetched page 2 of 6
Fetched page 3 of 6
Fetched page 4 of 6
Fetched page 5 of 6
Fetched page 6 of 6